// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"server/api/admin"
)

type ControllerAdminLogin struct{}

func NewAdminLogin() admin.IAdminAdminLogin {
	return &ControllerAdminLogin{}
}

type ControllerAdminMember struct{}

func NewAdminMember() admin.IAdminAdminMember {
	return &ControllerAdminMember{}
}

type ControllerAdminRole struct{}

func NewAdminRole() admin.IAdminAdminRole {
	return &ControllerAdminRole{}
}

type ControllerAdminSite struct{}

func NewAdminSite() admin.IAdminAdminSite {
	return &ControllerAdminSite{}
}

type ControllerGenCodes struct{}

func NewGenCodes() admin.IAdminGenCodes {
	return &ControllerGenCodes{}
}

type ControllerAdminMenu struct{}

func NewAdminMenu() admin.IAdminAdminMenu {
	return &ControllerAdminMenu{}
}
