// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// adminLoginLogDao is the data access object for the table admin_login_log.
// You can define custom methods on it to extend its functionality as needed.
type adminLoginLogDao struct {
	*internal.AdminLoginLogDao
}

var (
	// AdminLoginLog is a globally accessible object for table admin_login_log operations.
	AdminLoginLog = adminLoginLogDao{internal.NewAdminLoginLogDao()}
)

// Add your custom methods and functionality below.
