// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// appMemberDao is the data access object for the table app_member.
// You can define custom methods on it to extend its functionality as needed.
type appMemberDao struct {
	*internal.AppMemberDao
}

var (
	// AppMember is a globally accessible object for table app_member operations.
	AppMember = appMemberDao{internal.NewAppMemberDao()}
)

// Add your custom methods and functionality below.
