// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// hgAdminRoleDao is the data access object for the table hg_admin_role.
// You can define custom methods on it to extend its functionality as needed.
type hgAdminRoleDao struct {
	*internal.HgAdminRoleDao
}

var (
	// HgAdminRole is a globally accessible object for table hg_admin_role operations.
	HgAdminRole = hgAdminRoleDao{internal.NewHgAdminRoleDao()}
)

// Add your custom methods and functionality below.
