// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// hgUserDao is the data access object for the table hg_user.
// You can define custom methods on it to extend its functionality as needed.
type hgUserDao struct {
	*internal.HgUserDao
}

var (
	// HgUser is a globally accessible object for table hg_user operations.
	HgUser = hgUserDao{internal.NewHgUserDao()}
)

// Add your custom methods and functionality below.
